version: "3.9"
services:
  client:
    build:
      context: ./client
      dockerfile: dev.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/app/src
    container_name: client
    image: client
  server:
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./server/src:/app/src
    container_name: server
    image: server
